### ISSUE TITLE
Base maps

### ISSUE THREAD

**Issue by salampe** [ec-jrc/lisflood-lisvap#14]
In the base maps folder there are only three maps available. Is that sufficient for running lisvap for the two test cases?

**Comment by domeniconappo** [comment]
> I thought you had a case study with a number of days to run LISFLOOD for Europe? Where are those maps?
About LISFLOOD, I'm about to create a "smoke" test for it, same way as I've done for LISVAP, so with some input and reference results to compare.

Case studes/Test catchments will be useful as demo/showcase and users can play with them but for sure I will use some data from there. I still need to review current assets here https://github.com/ec-jrc/lisflood-usecases

**Comment by domeniconappo** [comment]
@salampe 
I've decided to add a command to the Docker that let copy those files from docker to host (user's computer) so she/he can easily replicate use cases.

something like:

`docker run -v /local/folder/:/input efas/lisvap:latest usecases`

The user will find meteo input files, base maps and xml settings inside the /local/folder/
