### ISSUE TITLE
Cannot produce NetCDF output

### ISSUE THREAD

**Issue by emiliano-gelati** [ec-jrc/lisflood-lisvap#15]
Output maps to be reported and related options were not parsed correctly in LisSettings._reported_maps (src/lisvap/utils/\_\_init\_\_.py). The argument "report_temp" of the function "_set_active_options" is iterated over (e.g. a list of strings containing the names of the maps to be reported), however it was passed as a string. This produced empty output dicts ("report_maps_all", "report_maps_steps", "report_maps_end") and no output netCDF file was produced.

The "output_var" and "unit" fields of "ReportedMap" (namedtuple) could not be read: see changes in src/lisvap/utils/output.py.

NetCDF variables defined on "lat" and "lon" dimensions could not be created: see changes in src/lisvap/utils/writers.py.

Tentative bug-fixes in ccbbd3d77b79935608e3bc7e22c9813e8e406f2c

Problems found while testing LISVAP (0225a57c976242e7cb48f05f3f44b890e85868a9) on the Global 0.1 degree setup (settings file attached).
[settings_Lorentz.xml](https://github.com/ec-jrc/lisflood-lisvap/files/3135662/settings_Lorentz.txt)

**Comment by domeniconappo** [comment]
merged

**Comment by domeniconappo** [comment]
Good practice for tests/pytest:

https://docs.pytest.org/en/latest/goodpractices.html#install-package-with-pip

Need to use pip install -e . in development, to link package to current code.
Otherwise tests will use currently installed pip package instead of actual code
