### ISSUE TITLE
Add git LFS requirements in docs

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-lisvap#16]
Our repos use GIT LFS to manage large files. Users must install git lfs on their dev environment before cloning repos, otherwise they won't have .nc files.

**Comment by valeriolorini** [comment]
When we setup the ec-jrc we looked at the plan/prices and we agreed for the 'team' plan with possibilities of using LFS, nevertheless LFS is pay-per-GB counting size in download/upload.
We should really use it for big data, maybe for some use case or for static_maps, and not open to everybody. We decided to cut maps and limit the time of simulations. I'd suggest to NOT make LFS a requirements else we could scare away potential users. I'd use normal distribution if the size of repo  is less than100 MB.

**Comment by domeniconappo** [comment]
Removed LSF support in lisflood repositories (except some private data repos)
