### ISSUE TITLE
Check units of solar radiation maps in settings file

### ISSUE THREAD

**Issue by emiliano-gelati** [ec-jrc/lisflood-lisvap#18]
The units of downward solar radiation are J m<sup>-2</sup>day<sup>-1</sup>, but the comment in the settings file entry reports `[W/m2]`: https://github.com/ec-jrc/lisflood-lisvap/blob/master/settings_tpl.xml#L124-L128

See equations at https://github.com/ec-jrc/lisflood-lisvap/blob/master/src/lisvap/lisvapdynamic.py#L198-L210

This could be misleading for input preparation

**Comment by domeniconappo** [comment]
@emiliano-gelati 
@menta78 

Hi Emiliano, good you raised this issue.

Not sure it's related and it makes sense to you: in CORDEX setup we have W/m2. Correct? Also, there is a kind of conversion in case of CORDEX dataset...how could we include both setups in that comment?

Check those snippets:
https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/src/lisvap/hydrological/readmeteo.py#L59-L66

and here:

https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/src/lisvap/hydrological/readmeteo.py#L106-L109

**Comment by emiliano-gelati** [comment]
`Rds` is read in as Wm<sup>-2</sup>, which is Js<sup>-1</sup>m<sup>-2</sup>, and then is converted to Jday<sup>-1</sup>m<sup>-2</sup> by the 86400 multiplication.

The entry `RdsMaps` appears in
https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/tests/data/tests_cordex.xml#L389-L393
but not in https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/settings_tpl.xml - should not it be there as well to be read when `<setoption name="CORDEX" choice="1" />`?
https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/src/lisvap/hydrological/readmeteo.py#L47-L66

**Comment by domeniconappo** [comment]
> `Rds` is read in as Wm-2, which is Js-1m-2, and then is converted to Jday-1m-2 by the 86400 multiplication.
> 
> The entry `RdsMaps` appears in
> https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/tests/data/tests_cordex.xml#L389-L393
> 
> 
> but not in https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/settings_tpl.xml - should not it be included in the settings file, so that `Rds` can be read if `<setoption name="CORDEX" choice="1" />`?

Yes, I guess so:) Could you take care of it in same branch you're developing for this issue?

The thing here is that for CORDEX, that parameter is supposed to have another unit so in the comment we need to underline that somehow...

**Comment by emiliano-gelati** [comment]
OK - I will add missing entries in  https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/settings_tpl.xml that are needed to run LISVAP when the option CORDEX is on.

**Comment by emiliano-gelati** [comment]
I have added the missing CORDEX forcing entries to https://github.com/ec-jrc/lisflood-lisvap/blob/bc28384453640e507b9f8256dcd5d513e746b22f/settings_tpl.xml (commit fd2e91799b2656ae55b83150d82a57d17f7f6847).

I have also added comments clarifying which forcing variables are used with CORDEX or EFAS options.

Unused Prefix* entries have been removed:
https://github.com/ec-jrc/lisflood-lisvap/commit/fd2e91799b2656ae55b83150d82a57d17f7f6847#diff-33331218443638d0d631161d05601fa3L91-L131

**Comment by emiliano-gelati** [comment]
branch https://github.com/ec-jrc/lisflood-lisvap/tree/18_solar_radiation_units_XML_comment merged into master
