### ISSUE TITLE
Problem with readers when variable has -9999 values

### ISSUE THREAD

**Issue by valeriolorini** [ec-jrc/lisflood-lisvap#24]
Long Net Wave radiation can have values such as  -9999 , we saw it in GloFAS.
The workaround is to not classify no_data the -9999 values for the variable rn.

**Comment by domeniconappo** [comment]
@valeriolorini can we close this?

**Comment by valeriolorini** [comment]
yes, but a better solution is needed fr handling such cases, as now it's rn allowing -9999 values but maybe we'll have other variables doing it in future.

**Comment by domeniconappo** [comment]
sure if it happens we'll think something more robust

**Comment by salampe** [comment]
Remember also that in the JIRA issue with the 1arcmin meteo maps we are using now a short integer with a scale offset. In this case the MV is -9999. I am not sure if this is related . In case not forget it.

**Comment by valeriolorini** [comment]
We already discussed a possible solution: to check the min value of the file to see if it's lower than the usual -9999 and in case using -99999999 when we load the map into a pcraster object.
