### ISSUE TITLE
installing LISVAP on JEODPP

### ISSUE THREAD

**Issue by farinfa** [ec-jrc/lisflood-lisvap#26]
Hello,
I'm trying to use LISVAP on the JEODPP platform. 
I am following your [instructions](https://ec-jrc.github.io/lisflood-lisvap/3_LISVAP_installation/) for the installation phase. Considering that 

> Option 1 - Pull the Docker image

 is not viable, because the docker tool cannot be used in JEODPP, I am giving a try to Options 2 and 3, but none of them are working.

> Option 2 - Install LISVAP python module using pip tool

- after making sure that the `virtualenv `is installed, i get to my project forlder and create my own virtual environment;
`cd project_folder`
`virtualenv venv`
venv succesfully created
`source venv/bin/activate`
`pip install lisflood-lisvap`

![image](https://user-images.githubusercontent.com/62378247/77052816-affc9680-69cd-11ea-86df-3dfec47f2333.png)

Similar situation if I try to go for 

> Option 3 -  Clone the repository from github

it stops at the first command
`git clone https://github.com/ec-jrc/lisflood-lisvap.git`
![image](https://user-images.githubusercontent.com/62378247/77053257-5d6faa00-69ce-11ea-9b54-52bba4b5d2c2.png)

Can you suggest a way to overtake these issues?
Thanks!

**Comment by domeniconappo** [comment]
Hi,
pip install lisflood-lisvap is the best way and should work fine.
Try to do the following (after you have activated the venv):

```bash
pip install -U pip
pip install lisflood-lisvap
```

if still not working, just try to install numpy first or any other package that setup is complaining is missing:

```
pip install numpy
pip install lisflood-lisvap
```

**Comment by farinfa** [comment]
Hi, thanks for the quick reaction.
Here what I get (sorry for the long post, but I thought you might want to see the full error messages):

> `pip install -U pip`

![image](https://user-images.githubusercontent.com/62378247/77057499-564b9a80-69d4-11ea-84f7-6ad122ba8382.png)


> `pip install lisflood-lisvap`

![image](https://user-images.githubusercontent.com/62378247/77057580-74b19600-69d4-11ea-9589-6f9e46e5a185.png)
 
> if still not working, just try to install numpy first or any other package that setup is complaining is missing:
> `pip install numpy`

![image](https://user-images.githubusercontent.com/62378247/77057664-9579eb80-69d4-11ea-97a6-52386dd6c852.png)

> `pip install lisflood-lisvap`

![image](https://user-images.githubusercontent.com/62378247/77057821-d2de7900-69d4-11ea-91ab-4074c87c03bf.png)
![image](https://user-images.githubusercontent.com/62378247/77057878-ea1d6680-69d4-11ea-98e1-b9e9e427b3a7.png)

then I tried to install manually also `cftime`
`pip install cftime`

![image](https://user-images.githubusercontent.com/62378247/77058010-2224a980-69d5-11ea-87ef-96c2e6d29e74.png)

**Comment by domeniconappo** [comment]
Hi,
is it a python2 venv or python3?

Try in same virtualenv to install cython first.

```
pip install cython
pip install cftime
pip install lisflood-lisvap
```

Let us know!

**Comment by farinfa** [comment]
It is a venv version 20.0.10 in python 3.5
![image](https://user-images.githubusercontent.com/62378247/77061375-6bc3c300-69da-11ea-8c7b-12bbc883c3ba.png)

`pip install cython`
works fine
![image](https://user-images.githubusercontent.com/62378247/77061546-b34a4f00-69da-11ea-9639-0e24b2d1fb03.png)

`pip install cftime`
instead, gives problems
![image](https://user-images.githubusercontent.com/62378247/77061635-db39b280-69da-11ea-8dba-4ba40048a969.png)
![image](https://user-images.githubusercontent.com/62378247/77061681-edb3ec00-69da-11ea-8c74-a9aa237d7bed.png)

**Comment by domeniconappo** [comment]
Could you report the output of the following?
`gcc --version`

**Comment by farinfa** [comment]
> gcc --version

![image](https://user-images.githubusercontent.com/62378247/77064979-bc3e1f00-69e0-11ea-9173-3bcdffec4a06.png)

I tried to install gcc
`pip install gcc`
but
![image](https://user-images.githubusercontent.com/62378247/77065056-de37a180-69e0-11ea-9a3a-9ec5bb0f2198.png)

**Comment by domeniconappo** [comment]
That is the system compiler and it is missing on JEODPP, it seems. You can't install it as a normal user.
Maybe you have to activate the module? I suggest to contact JEODPP support to ask for gcc. You can report to them that some python packages (ie. cftime) need compilation during installation.

**Comment by farinfa** [comment]
ok, thanks a lot @domeniconappo 

It worked!
![image](https://user-images.githubusercontent.com/62378247/77073930-5194df80-69f0-11ea-84a4-1bca5e9fe4ed.png)

**Comment by domeniconappo** [comment]
Thanks for reporting @farinfa !
Could you also give some details about how you fixed it?

Thank you!

**Comment by farinfa** [comment]
I just did what you suggested: I asked JEODPP colleagues to grant me access to a `custom/jeodpp-terminal` where I had the right to use the compiler, and the commands you suggested just worked fine.

Summarizing, the sequence was:

1- get the access to a `custom/jeodpp-terminal` where the user has access to a compiler (need to ask to JEODPP team)

2- create the virtual environment in the folder project:
`cd folder project`
`virtualenv venv`
`source venv/bin/activate`

3- get into the virtual env folder and install all the packages
`cd venv`
`pip install numpy`
`pip install cython`
`pip install cftime`
`pip install lisflood-lisvap`

**Comment by farinfa** [comment]
Hi @domeniconappo, sorry to bother you again with this.

Even if I finally managed to install Lisvap using the procedure above, I never managed to make it run on JEODPP. The main problem lies on the fact that I need to install manually the `pcraster` package.  The only way they let me do that is by using a `conda virtual environment`.  My problem now is that I have Lisvap in a virtual environment and `pcraster ` in another one.
Would it be possible in your opinion to install Lisvap in a `conda virtual env`?
Thanks

**Comment by domeniconappo** [comment]
Hi @farinfa 
can you try to use PYTHONPATH env variable?

Basically, you just export the path to pcraster python package. Python interpreter will add the library to your environment.

```export PYTHONPATH=/path/to/pcraster/python/folder```

If you don't know the exact path, you can:

1. activate the conda virtualenv
2. enter python shell (type `python`)
3. ```import pcraster; pcraster.__file__```

It will print a path; you need the path without pcraster/\_\_init\_\_.py

e.g. in my system I've installed pcraster in /opt/pcraster36 so for me the output will be `/opt/pcraster36/python/pcraster/__init__.py` so I set `PYTHONPATH=/opt/pcraster36/python/` before to activate my virtualenv and launch any program that use pcraster python library.

I'm not used to conda env so I'm not sure it will work...maybe some dependencies will be missing. don't know.

Please give it a try and let us know.

**Comment by domeniconappo** [comment]
If that doesn't work, another option would be to put lisvap on conda repository....but I 'll need time for that.

**Comment by farinfa** [comment]
Sorted, thanks!

I installed Lisvap inside the `conda virtual environment` after installing the pc raster and it works, here the full procedure:

Summarizing, here what I did to install LISVAP using '*Option 2 - Install LISVAP python module using pip tool*' from the LISVAP installation guide ([here](https://ec-jrc.github.io/lisflood-lisvap/3_LISVAP_installation/)).

The steps to be followed are:

1- get the access to a `custom/jeodpp-terminal` where the user has access to a compiler (need to ask to JEODPP team)

2- create a `conda virtual environment` as @hasenpa suggested [here](https://jeodpp.jrc.ec.europa.eu/apps/gitlab/for-everyone/support/issues/124#note_9769):

>  1. Open a shell
>    1. as written in https://jeodpp.jrc.ec.europa.eu/apps/gitlab/for-everyone/documentation/-/wikis/Jeodpp_services/Jeodesk/JEODPP-Desktop-Terminal-Service#user-installation-of-python-packages-with-miniconda-virtual-environments type `conda create -m -p /eos/jeodpp/home/users/USERNAME_HERE/conda_lisvap` and confirm installation (do not try to update conda, it works as it is)
>    2. Then type `conda activate /eos/jeodpp/home/users/USERNAME_HERE/conda_lisvap` In my case, I received a message telling me that I had to initialise by conda shell first (I chose bash as shell) by typing `conda init bash`
> 2. Close your shell as instructed if you had to initialise your conda shell and open a new one.
>    1. Activate your conda environment by typing `conda activate /eos/jeodpp/home/users/USERNAME_HERE/conda_lisvap/`

Type:

`conda config --add channels conda-forge`

>     2. Type `conda install pcraster` and validate. It displays a long list of packages to install and starts the installation process. The whole process takes a long time.

3- Once the `pcraster` is installed, get into the virtual env folder and install all the packages

`cd /eos/jeodpp/home/users/USERNAME_HERE/conda_lisvap`

`pip install numpy`

`pip install cython`

`pip install cftime`

`pip install lisflood-lisvap`

This installation runs successfully. Now you have both Lisvap and `pcraster` in the same virtual environment, so you can create your `settings.xml` and run the model.
If it gives a `permission denied` message, then:

get into the `bin` folder in your virtual env

`cd /eos/jeodpp/home/users/USERNAME_HERE/conda_lisvap/bin`

and type

`chmod +x lisvap`

**Comment by domeniconappo** [comment]
@farinfa 
Amazing. Thanks for sharing!!

**Comment by domeniconappo** [comment]
@farinfa 
just one thing for you: you don't need to go into virtualenv folder to install packages.
It's enough to activate the virtualenv. Then, the virtualenv pip will install packages in virtualenv packages folder.
So this is not necessary:

> get into the virtual env folder and install all the packages
> `cd /eos/jeodpp/home/users/USERNAME_HERE/conda_lisvap`

**Comment by farinfa** [comment]
ok, thanks!
