### ISSUE TITLE
Grid discrepancy error in Lisvap

### ISSUE THREAD

**Issue by farinfa** [ec-jrc/lisflood-lisvap#27]
Hi,

I'm having an error while running Lisvap and I don't manage to understand where the problem is. 
![image](https://user-images.githubusercontent.com/62378247/77751537-3183a280-7026-11ea-93e0-5bc347bc1d82.png)
It complains about the difference in the grids of my input files, but actually the grids are the same...

tmin.nc grid:
![image](https://user-images.githubusercontent.com/62378247/77751370-db166400-7025-11ea-871b-ea48eb4a1a33.png)

area.nc grid:
![image](https://user-images.githubusercontent.com/62378247/77751471-144ed400-7026-11ea-953f-047167a2d01c.png)

What am I getting wrong?
Thanks a lot and sorry to bother with this.

Fabio

**Comment by domeniconappo** [comment]
I'm going to check the code...indeed it should be ok.
Maybe a rounding problem for coordinates. I remember we had a similar issue with lisflood but not sure.

is there any chance you can send me or share somewhere those two files? I guess tmin.nc is a big file but with CDO you can reduce the size by selecting just one timestep...

**Comment by farinfa** [comment]
All the files are inside the JEODPP: I could reduce the file size, but I cannot get them out of there... 
I should download again the files from the ESGF repository and process them again, but, still, I would not be able to get the very same area.nc file.

**Comment by domeniconappo** [comment]
@farinfa Maybe I've spot an inconsistency in the code, which leads to a problem when cellSize (xinc) has more than 4 decimals and there is a difference when rounding to 4 and 5. This didn't cause a problem in our datasets so far. 
But this is just a guess as I don't have your setup to check...

I will fix this bug anyway and publish the new minor release. You will need to install lisvap again with:
```bash
pip install -U lisflood-lisvap
```
and then run it again to see if the problem goes away...

Otherwise we need to find another way on how to debug this issue.

I will tell you when new release is published.

**Comment by domeniconappo** [comment]
Hi @farinfa 
lisflood-lisvapp 0.4.4 is there. Please give it a try.
You just need to upgrade the package in your existing virtual environment (i.e. you don't have to repeat the installation procedure again, of course :))

to update to latest version:

`pip install -U lisflood-lisvap`

Or if you prefer to specify the version, the tag is 0.4.4

`pip install "lisflood-lisvap==0.4.4"`

Let us know!!!

**Comment by farinfa** [comment]
Yep, it works now! I'm having another issue but is totally related to my settings XML. Thanks a lot @domeniconappo !

Side note, in the update process there is a minor error in the final message. It says it installed version 0.4.3, while when you run it it says correctly 0.4.4
![image](https://user-images.githubusercontent.com/62378247/77760756-2dac4c00-7037-11ea-9740-7df5511efc41.png)

**Comment by domeniconappo** [comment]
@farinfa 
great!
thanks for reporting the issue...it seems related to the fact that lisvap is already installed and it takes the version from current package, before the update. Thanks for reporting.

Don't hesitate to open another issue if you need help with settings.xml

**Comment by farinfa** [comment]
thanks!
