### ISSUE TITLE
365_day calendar in Lisvap

### ISSUE THREAD

**Issue by farinfa** [ec-jrc/lisflood-lisvap#43]
Hi, 
I'm experiencing some issues while running LISVAP with "365_day" calendar inputs. 
![image](https://user-images.githubusercontent.com/62378247/122074221-52860e00-cdf9-11eb-982d-ec8c75211eb6.png)

I know that this was changed/improved with the latest update of the model: is there something I have to specify in the settings? 

Thanks!

**Comment by farinfa** [comment]
any reaction on this?

**Comment by gnrgomes** [comment]
Hi @farinfa,
I'll look into your issue, ASAP.
This issue seems to be related with the processing of a leap year data file.
It would be great if you could share the "problematic" input and setting files with me. But I'll try to reproduce this here by faking some input with that calendar type over a leap year to see if I can get the same exception.

**Comment by farinfa** [comment]
Hi @gnrgomes 

My input files are huge: I can try to cut a slice of about 5/10 years and try to forward the filesto you.
I'll keep you posted on that.
Thanks

**Comment by gnrgomes** [comment]
Hi @farinfa,
Probably it would be enough only 2 or 3 years of data where one of the years is a leap year.

**Comment by farinfa** [comment]
Hi @gnrgomes,

you can find the files and the settings at the following [link ](http://jeodpp.jrc.ec.europa.eu/ftp/private/zyWEfe5Am/kFR4bCtFZRhs3YaL/shared/)
the paths in the settings file need to be adjusted.
Thank you for your support.

**Comment by gnrgomes** [comment]
Hi @farinfa,
I was able to correct the issue and Monday I will deploy a new version that deals with non Gregorian calendars.
It will read the calendar type from the input files.

I'll let you know when the new version is ready.

**Comment by farinfa** [comment]
Hi @gnrgomes, 
Thank you very much!

**Comment by gnrgomes** [comment]
Hi @farinfa 
Could you please try the new version lisflood-lisvap==1.0.4 that now also processes files with calendar type different from prolepetic_gregorian?
Basically, Lisvap will read the calendar type from the first meteo input file that it reads and produces the output files (e0, es, et) using the same calendar type. No need for changes on the settings file.
This assumes that all the meteo input files are consistent and use the same calendar type.

Please, let me know how it went.

Thank you

**Comment by farinfa** [comment]
Lisflood-lisvap version 1.0.4 fixes this issue. The only discrepancy I see is that it generates leap years files with 366 days with a 365_day calendar (see the ncdump report of a 1952 file for instance)
![image](https://user-images.githubusercontent.com/62378247/127493042-3cad4bb7-c3e5-4f03-b57e-ceef2939dc7a.png)

**Comment by gnrgomes** [comment]
This happens because the dates are at the end of the interval and when I separate the files by year, I include the first day of the next year and this is a requirement for us. The last date of a file and the first date of the next file, should be consecutive.
