### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-lisvap#5]
This task will be carried out in two phases:

1. make code py2 and py3 compatible, by using a compatibility package (six/nine, python-future)
2. remove py2 support after January 2020

**Comment by domeniconappo** [comment]
Code is now compatible with python2.7 and python3 (>=3.5).

Used nine package in order to write python3 code that is compatible with python2 (instead of using six to make python2 code compatible with python3)...
Docker image was also updated to python3.5 (there is an issue with python3.6 docker image). I'll try to update to python3.7 image next weeks.

Added a tox tests configuration for all supported python environments.

Main issues addressed...
1. print statements (`from __future__ import print_function`)
2. range function calls (`from nine import range`)
3. map function calls (`from nine import map`)
4. dict.items() calls (`from future import listitems` and use as listitems(mydict) instead of calling mydict.items() and accessing by index to elements (raise errors in python3).

**Comment by salampe** [comment]
Excellent! @domeniconappo
