### ISSUE TITLE
missing pyproj in install requirements

### ISSUE THREAD

**Issue by r3dmos** [ec-jrc/lisflood-lisvap#59]
https://github.com/ec-jrc/lisflood-lisvap/blob/2bceb72a7bb2c66ef102f35d37414ddec64b84d1/setup.py#L112

Hello,
is it possible that pyproj is missing in this line?
I've tried to install lisvap using pip and when I tried to run it it could not import the pyproj package because it was missing.
I solved the issue by installing pyproj and pcraster using conda and then pip install lisvap.

**Comment by gnrgomes** [comment]
Hello,
Thank you for spotting this.
You can use the requirements.txt to get your environment ready, which includes pyproj.
I will see if adding pyproj to setup.py will solve the issue.
